# Generated by Django 4.2.7 on 2025-11-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Комбинация IP + browser fingerprint",
                        max_length=255,
                        unique=True,
                        verbose_name="Уникальный идентификатор сессии",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "browser_fingerprint",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Browser fingerprint"
                    ),
                ),
                (
                    "has_completed",
                    models.BooleanField(default=False, verbose_name="Опрос завершен"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало прохождения"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия студента",
                "verbose_name_plural": "Сессии студентов",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="survey_surv_session_e2cfb9_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="survey_surv_ip_addr_b9bd35_idx"
                    ),
                    models.Index(
                        fields=["has_completed"], name="survey_surv_has_com_b2b3d8_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="response",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="survey.surveysession",
                verbose_name="Сессия",
            ),
        ),
    ]
